[dugganusa:stix]
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
TIME_FORMAT = %Y-%m-%dT%H:%M:%S
TIME_PREFIX = "timestamp"\s*:\s*"
MAX_TIMESTAMP_LOOKAHEAD = 30
TRUNCATE = 999999

# CIM Threat Intelligence data model mappings
FIELDALIAS-threat_type = threat_type AS threat_category
FIELDALIAS-indicator = value AS threat_match_value
FIELDALIAS-source = source AS threat_source
FIELDALIAS-confidence = confidence AS threat_confidence
FIELDALIAS-malware = malware_family AS threat_group
